Repository Chilli-Saewoo/Roll-in, pull requests merged in 2022-11, with the labels that each got.

#44 아이패드에서 페이지 컨트롤을 추가합니다
  HalloweenTF_iPad/HalloweenTF_iPad/ContentView.swift
Labels: feature

#47 그룹 생성 시 그룹 이름을 받는 뷰를 생성했습니다.
  Rollin_MVP/Rollin_MVP.xcodeproj/project.pbxproj
  Rollin_MVP/Rollin_MVP/Screens/Base.lproj/Main.storyboard
  Rollin_MVP/Rollin_MVP/Screens/CreateGroup/SetGroupNameViewController.swift
Labels: feature

#53 유저가 그룹을 생성할 때 닉네임을 설정하고 그룹명과 생성일자를 확인할 수 있습니다.
  Rollin_MVP/Rollin_MVP.xcodeproj/project.pbxproj
  Rollin_MVP/Rollin_MVP/Global/Extension+/Date+.swift
  Rollin_MVP/Rollin_MVP/Model/CreatingGroup/CreatingGroupInfo.swift
  Rollin_MVP/Rollin_MVP/Screens/Base.lproj/Main.storyboard
  Rollin_MVP/Rollin_MVP/Screens/CreateGroup/ConfirmGroupViewController.swift
  Rollin_MVP/Rollin_MVP/Screens/CreateGroup/GroupCodeSharingViewController.swift
  Rollin_MVP/Rollin_MVP/Screens/CreateGroup/SetGroupNameWhileCreatingGroupViewController.swift
  Rollin_MVP/Rollin_MVP/Screens/CreateGroup/SetNicknameWhileCreatingGroupViewController.swift
  Rollin_MVP/Rollin_MVP/Screens/CreateGroup/ViewComponents/ConfirmGroupCardView.swift
Labels: feature

#62 UIViewController 의 Alert extension 을 추가합니다
  Rollin_MVP/Rollin_MVP.xcodeproj/project.pbxproj
  Rollin_MVP/Rollin_MVP/Global/Extension/Alert+.swift
Labels: feature

#55 firebase와 애플로그인 연동을 구현한다
  RollIn/RollIn.xcodeproj/xcshareddata/xcschemes/RollIn.xcscheme
  Rollin_MVP/Rollin_MVP.xcodeproj/project.pbxproj
  Rollin_MVP/Rollin_MVP/Rollin_MVP.entitlements
  Rollin_MVP/Rollin_MVP/Rollin_MVPRelease.entitlements
  Rollin_MVP/Rollin_MVP/Screens/AppleLogin/LoginViewController.swift
  Rollin_MVP/Rollin_MVP/Screens/Base.lproj/Main.storyboard
Labels: feature

#60 작성 UI 레이아웃 구현
  Rollin_MVP/Rollin_MVP.xcodeproj/project.pbxproj
  Rollin_MVP/Rollin_MVP/Global/Extension+/Alert+.swift
  Rollin_MVP/Rollin_MVP/Global/Extension+/NSObject+.swift
  Rollin_MVP/Rollin_MVP/Screens/Base.lproj/Main.storyboard
  Rollin_MVP/Rollin_MVP/Screens/WriteRollingPaper/View/PostThemePickerView.swift
  Rollin_MVP/Rollin_MVP/Screens/WriteRollingPaper/View/PostThemePickerViewCell.swift
  Rollin_MVP/Rollin_MVP/Screens/WriteRollingPaper/View/PostView.swift
  Rollin_MVP/Rollin_MVP/Screens/WriteRollingPaper/WriteRollingPaperViewController.swift
Labels: feature

#64 롤링페이퍼 작성하기 뷰에서 사진 등록을 구현합니다
  Rollin_MVP/Rollin_MVP.xcodeproj/project.pbxproj
  Rollin_MVP/Rollin_MVP/Screens/WriteRollingPaper/View/PostView.swift
  Rollin_MVP/Rollin_MVP/Screens/WriteRollingPaper/WriteRollingPaperViewController.swift
Labels: feature

#67 HalfModal 안에 상세 포스트를 보여줄 Carousel을 적용합니다.
  Rollin_MVP/Rollin_MVP.xcodeproj/project.pbxproj
  Rollin_MVP/Rollin_MVP/Screens/DetailRollingPaper/DetailPostCollectionViewCell.swift
  Rollin_MVP/Rollin_MVP/Screens/DetailRollingPaper/DetailRollingPaperViewController.swift
  Rollin_MVP/Rollin_MVP/Screens/DetailRollingPaper/RollingPaperView.swift
  Rollin_MVP/Rollin_MVP/Screens/RollingPaperDetail/DetailRollingPaperViewController.swift
Labels: feature

#68 롤링페이퍼 작성하기 뷰 하이파이 디자인 적용
  RollIn/RollIn.xcodeproj/xcshareddata/xcschemes/RollIn.xcscheme
  Rollin_MVP/Rollin_MVP.xcodeproj/project.pbxproj
  Rollin_MVP/Rollin_MVP/Global/Extension+/UIColor+.swift
  Rollin_MVP/Rollin_MVP/Resources/Assets.xcassets/Colors/Contents.json
  Rollin_MVP/Rollin_MVP/Resources/Assets.xcassets/Colors/bgBlue.colorset/Contents.json
  Rollin_MVP/Rollin_MVP/Resources/Assets.xcassets/Colors/bgGreen.colorset/Contents.json
  Rollin_MVP/Rollin_MVP/Resources/Assets.xcassets/Colors/bgPurple.colorset/Contents.json
  Rollin_MVP/Rollin_MVP/Resources/Assets.xcassets/Colors/bgRed.colorset/Contents.json
  Rollin_MVP/Rollin_MVP/Resources/Assets.xcassets/Colors/bgYellow.colorset/Contents.json
  Rollin_MVP/Rollin_MVP/Resources/Assets.xcassets/Colors/inactiveBgGray.colorset/Contents.json
  Rollin_MVP/Rollin_MVP/Resources/Assets.xcassets/Colors/inactiveTextGray.colorset/Contents.json
  Rollin_MVP/Rollin_MVP/Resources/Assets.xcassets/Colors/systemBlack.colorset/Contents.json
  Rollin_MVP/Rollin_MVP/Resources/Assets.xcassets/Colors/textBlue.colorset/Contents.json
  Rollin_MVP/Rollin_MVP/Resources/Assets.xcassets/Colors/textGreen.colorset/Contents.json
  Rollin_MVP/Rollin_MVP/Resources/Assets.xcassets/Colors/textPurple.colorset/Contents.json
  Rollin_MVP/Rollin_MVP/Resources/Assets.xcassets/Colors/textRed.colorset/Contents.json
  Rollin_MVP/Rollin_MVP/Resources/Assets.xcassets/Colors/textYellow.colorset/Contents.json
  Rollin_MVP/Rollin_MVP/Rollin_MVP.entitlements
  Rollin_MVP/Rollin_MVP/Rollin_MVPRelease.entitlements
  Rollin_MVP/Rollin_MVP/Screens/AppleLogin/LoginViewController.swift
  Rollin_MVP/Rollin_MVP/Screens/Base.lproj/Main.storyboard
  Rollin_MVP/Rollin_MVP/Screens/WriteRollingPaper/View/PostThemePickerView.swift
  Rollin_MVP/Rollin_MVP/Screens/WriteRollingPaper/View/PostThemePickerViewCell.swift
  Rollin_MVP/Rollin_MVP/Screens/WriteRollingPaper/View/PostView.swift
  Rollin_MVP/Rollin_MVP/Screens/WriteRollingPaper/WriteRollingPaperViewController.swift
Labels: feature

#78 FireStore에 새 그룹을 추가하는 로직을 완성하였습니다.
  Rollin_MVP/Rollin_MVP/Screens/AppMain/MainViewController.swift
  Rollin_MVP/Rollin_MVP/Screens/CreateGroup/ConfirmGroupViewController.swift
  Rollin_MVP/Rollin_MVP/Screens/CreateGroup/SetGroupNameWhileCreatingGroupViewController.swift
Labels: feature

#75 롤링페이퍼 모달뷰의 디테일을 수정합니다.
  Rollin_MVP/Rollin_MVP/Screens/Base.lproj/Main.storyboard
  Rollin_MVP/Rollin_MVP/Screens/DetailRollingPaper/DetailRollingPaperViewController.swift
  Rollin_MVP/Rollin_MVP/Screens/DetailRollingPaper/RollingPaperView.swift
Labels: feature

#70 주변 터치시에 키보드 dismiss 기능 extension 추가
  Rollin_MVP/Rollin_MVP.xcodeproj/project.pbxproj
  Rollin_MVP/Rollin_MVP/Global/Extension+/UIViewController+.swift
Labels: feature

#85 그룹 추가하기 플로우에 하이파이 디자인을 적용하였습니다.
  Rollin_MVP/Rollin_MVP.xcodeproj/project.pbxproj
  Rollin_MVP/Rollin_MVP/Global/Extension+/Date+.swift
  Rollin_MVP/Rollin_MVP/Global/Extension+/Int+.swift
  Rollin_MVP/Rollin_MVP/Global/Extension+/String+.swift
  Rollin_MVP/Rollin_MVP/Resources/Assets.xcassets/Colors/inactiveTextGray.colorset/Contents.json
  Rollin_MVP/Rollin_MVP/Resources/Assets.xcassets/Colors/systemBlack.colorset/Contents.json
  Rollin_MVP/Rollin_MVP/Screens/CreateGroup/ConfirmGroupViewController.swift
  Rollin_MVP/Rollin_MVP/Screens/CreateGroup/GroupCodeSharingViewController.swift
  Rollin_MVP/Rollin_MVP/Screens/CreateGroup/SetGroupNameWhileCreatingGroupViewController.swift
  Rollin_MVP/Rollin_MVP/Screens/CreateGroup/SetNicknameWhileCreatingGroupViewController.swift
  Rollin_MVP/Rollin_MVP/Screens/CreateGroup/SetThemeViewController.swift
  Rollin_MVP/Rollin_MVP/Screens/CreateGroup/ViewComponents/GroupCodeView.swift
  Rollin_MVP/Rollin_MVP/Screens/GroupWithThemeView.swift
Labels: feature

#83 동적 컬렉션뷰 생성 및 로그인 로직 추가
  Rollin_MVP/Rollin_MVP.xcodeproj/project.pbxproj
  Rollin_MVP/Rollin_MVP/App/SceneDelegate.swift
  Rollin_MVP/Rollin_MVP/Model/PostRollingPaper/PostRollingPaperModel.swift
  Rollin_MVP/Rollin_MVP/Rollin_MVP.entitlements
  Rollin_MVP/Rollin_MVP/Screens/AppleLogin/LoginViewController.swift
  Rollin_MVP/Rollin_MVP/Screens/Base.lproj/Main.storyboard
  Rollin_MVP/Rollin_MVP/Screens/ReadRollingPaper/PostRollingPaperLayout/PostRollingPaperLayout.swift
  Rollin_MVP/Rollin_MVP/Screens/ReadRollingPaper/PostRollingPaperView/PostRollingPaperCollectionViewCell.swift
  Rollin_MVP/Rollin_MVP/Screens/ReadRollingPaper/PostRollingPaperViewContoller/PostViewController.swift
  Rollin_MVP/Rollin_MVP/Screens/SetNickname/SetNicknameWhileLoginViewController.swift
Labels: feature, fix logic

#88 메인화면에 유저가 가입한 그룹들이 떠있게됩니다.
  Rollin_MVP/Rollin_MVP.xcodeproj/project.pbxproj
  Rollin_MVP/Rollin_MVP/Global/Extension+/NSTextAttachment+.swift
  Rollin_MVP/Rollin_MVP/Model/Group.swift
  Rollin_MVP/Rollin_MVP/Screens/AppMain/MainViewController.swift
  Rollin_MVP/Rollin_MVP/Screens/AppMain/ViewComponents/MainGroupCardViewCell.swift
Labels: feature

#91 그룹 참여플로우 UI를 구현하였습니다.
  Rollin_MVP/Rollin_MVP.xcodeproj/project.pbxproj
  Rollin_MVP/Rollin_MVP/App/SceneDelegate.swift
  Rollin_MVP/Rollin_MVP/Model/ParticipateGroupInfo.swift
  Rollin_MVP/Rollin_MVP/Screens/AppMain/MainViewController.swift
  Rollin_MVP/Rollin_MVP/Screens/AppMain/ViewComponents/AddGroupButtonBackgroundView.swift
  Rollin_MVP/Rollin_MVP/Screens/AppleLogin/LoginViewController.swift
  Rollin_MVP/Rollin_MVP/Screens/Base.lproj/Main.storyboard
  Rollin_MVP/Rollin_MVP/Screens/CreateGroup/ViewComponents/GroupCodeView.swift
  Rollin_MVP/Rollin_MVP/Screens/ParticiapteGroup/ConfirmGroupWhileParticipateViewController.swift
  Rollin_MVP/Rollin_MVP/Screens/ParticiapteGroup/SearchGroupWithCodeViewController.swift
  Rollin_MVP/Rollin_MVP/Screens/ParticiapteGroup/SetNicknameWhileParticipateViewController.swift
  Rollin_MVP/Rollin_MVP/Screens/ParticiapteGroup/ViewComponents/ParticipateGroupConfirmCardView.swift
Labels: feature

#93 유저가 그룹에 참가할 때 사용하게 될 firestore 업데이트 로직을 추가했습니다.
  Rollin_MVP/Rollin_MVP/Screens/ParticiapteGroup/SetNicknameWhileParticipateViewController.swift
Labels: feature

#95 머지 하면서 생긴 파일 유령화를 해결합니다!
  Rollin_MVP/Rollin_MVP.xcodeproj/project.pbxproj
  Rollin_MVP/Rollin_MVP/Model/Group.swift
  Rollin_MVP/Rollin_MVP/Screens/AppMain/ViewComponents/MainGroupCardViewCell.swift
  Rollin_MVP/Rollin_MVP/Screens/Base.lproj/Main.storyboard
  Rollin_MVP/Rollin_MVP/Screens/ParticipateGroup/ConfirmGroupWhileParticipateViewController.swift
  Rollin_MVP/Rollin_MVP/Screens/ParticipateGroup/SearchGroupWithCodeViewController.swift
  Rollin_MVP/Rollin_MVP/Screens/ParticipateGroup/SetNicknameWhileParticipateViewController.swift
  Rollin_MVP/Rollin_MVP/Screens/ParticipateGroup/ViewComponents/ParticipateGroupConfirmCardView.swift
Labels: bug

#80 롤링페이퍼 작성하기를 통해 파이어베이스에 업로드 구현
  Rollin_MVP/Rollin_MVP.xcodeproj/project.pbxproj
  Rollin_MVP/Rollin_MVP/Firebase/API/FirebaseStorageManager.swift
  Rollin_MVP/Rollin_MVP/Firebase/API/RollingPaperPostAPI.swift
  Rollin_MVP/Rollin_MVP/Model/RollingPaper/RollingPaperPostModel.swift
  Rollin_MVP/Rollin_MVP/Model/RollingPaperPostModel.swift
  Rollin_MVP/Rollin_MVP/Screens/WriteRollingPaper/View/PostThemePickerView.swift
  Rollin_MVP/Rollin_MVP/Screens/WriteRollingPaper/View/PostThemePickerViewCell.swift
  Rollin_MVP/Rollin_MVP/Screens/WriteRollingPaper/View/PostView.swift
  Rollin_MVP/Rollin_MVP/Screens/WriteRollingPaper/WriteRollingPaperViewController.swift
Labels: feature

#82 hide keyboard 함수 롤링페이퍼 작성 페이지에 선언
  Rollin_MVP/Rollin_MVP.xcodeproj/project.pbxproj
  Rollin_MVP/Rollin_MVP/Screens/Base.lproj/Main.storyboard
  Rollin_MVP/Rollin_MVP/Screens/WriteRollingPaper/WriteRollingPaperViewController.swift
Labels: feature

#96 하이파이 기반 로그인뷰 수정
  Rollin_MVP/Rollin_MVP.xcodeproj/project.pbxproj
  Rollin_MVP/Rollin_MVP/App/SceneDelegate.swift
  Rollin_MVP/Rollin_MVP/Global/Extension+/String+.swift
  Rollin_MVP/Rollin_MVP/Screens/AppleLogin/LoginViewController.swift
  Rollin_MVP/Rollin_MVP/Screens/LoginSetNickName/SetNickNameWhileLoginViewController.swift
Labels: fix ui

#98 Navigation Bar Back Button을 hi-fi에 맞춰 커스텀했습니다
  Rollin_MVP/Rollin_MVP.xcodeproj/project.pbxproj
  Rollin_MVP/Rollin_MVP/Screens/AppMain/MainViewController.swift
  Rollin_MVP/Rollin_MVP/Screens/CreateGroup/SetGroupNameWhileCreatingGroupViewController.swift
  Rollin_MVP/Rollin_MVP/Screens/CreateGroup/SetNicknameWhileCreatingGroupViewController.swift
  Rollin_MVP/Rollin_MVP/Screens/CreateGroup/SetThemeViewController.swift
  Rollin_MVP/Rollin_MVP/Screens/ParticipateGroup/ConfirmGroupWhileParticipateViewController.swift
  Rollin_MVP/Rollin_MVP/Screens/ParticipateGroup/SearchGroupWithCodeViewController.swift
Labels: fix ui

#103 상세보기 페이지 UI를 업데이트하였습니다.
  Rollin_MVP/Rollin_MVP/Global/Extension+/UIColor+.swift
  Rollin_MVP/Rollin_MVP/Resources/Assets.xcassets/Colors/cardBlue.colorset/Contents.json
  Rollin_MVP/Rollin_MVP/Resources/Assets.xcassets/Colors/cardDeepBlue.colorset/Contents.json
  Rollin_MVP/Rollin_MVP/Resources/Assets.xcassets/Colors/cardGreen.colorset/Contents.json
  Rollin_MVP/Rollin_MVP/Resources/Assets.xcassets/Colors/cardPink.colorset/Contents.json
  Rollin_MVP/Rollin_MVP/Resources/Assets.xcassets/Colors/cardPurple.colorset/Contents.json
  Rollin_MVP/Rollin_MVP/Resources/Assets.xcassets/Colors/cardRed.colorset/Contents.json
  Rollin_MVP/Rollin_MVP/Resources/Assets.xcassets/Colors/cardYellow.colorset/Contents.json
  Rollin_MVP/Rollin_MVP/Screens/GroupDetailView/GroupDetailViewController.swift
Labels: feature

#102 hi-fi에 변경에 따라 Navigationbar back button을 추가/변경하고 버튼 ui를 수정합니다
  Rollin_MVP/Rollin_MVP/Screens/CreateGroup/SetNicknameWhileCreatingGroupViewController.swift
  Rollin_MVP/Rollin_MVP/Screens/CreateGroup/SetThemeViewController.swift
  Rollin_MVP/Rollin_MVP/Screens/GroupDetailView/GroupDetailViewController.swift
  Rollin_MVP/Rollin_MVP/Screens/ParticipateGroup/ConfirmGroupWhileParticipateViewController.swift
Labels: fix ui

#104 하이파이 기반 동적 컬렉션뷰 수정
  Rollin_MVP/Rollin_MVP.xcodeproj/project.pbxproj
  Rollin_MVP/Rollin_MVP/Model/PostRollingPaper/PostRollingPaperModel.swift
  Rollin_MVP/Rollin_MVP/Resources/Assets.xcassets/pencil.imageset/Contents.json
  Rollin_MVP/Rollin_MVP/Resources/Assets.xcassets/pencil.imageset/Image.png
  Rollin_MVP/Rollin_MVP/Resources/Assets.xcassets/plus.imageset/Contents.json
  Rollin_MVP/Rollin_MVP/Resources/Assets.xcassets/plus.imageset/plus.svg
  Rollin_MVP/Rollin_MVP/Screens/Base.lproj/Main.storyboard
  Rollin_MVP/Rollin_MVP/Screens/PostRollingPaper/PostRollingPaperLayout/PostRollingPaperLayout.swift
  Rollin_MVP/Rollin_MVP/Screens/PostRollingPaper/PostRollingPaperView/PostRollingPaperCollectionViewCell.swift
  Rollin_MVP/Rollin_MVP/Screens/PostRollingPaper/PostRollingPaperViewContoller/PostViewController.swift
  Rollin_MVP/Rollin_MVP/Screens/WriteRollingPaper/WriteRollingPaperViewController.swift
Labels: feature

#119 그룹 생성/참가하기에서 공통적으로 사용되는 컴포넌트를 구현한 GroupBaseVC를 추가합니다
  Rollin_MVP/Rollin_MVP.xcodeproj/project.pbxproj
  Rollin_MVP/Rollin_MVP/Screens/Base/GroupBaseViewController.swift
Labels: feature

#123 GroupBaseViewController를 하위 ViewController 들에서 상속받습니다.
  Rollin_MVP/Rollin_MVP/Screens/Base/GroupBaseViewController.swift
  Rollin_MVP/Rollin_MVP/Screens/CreateGroup/ConfirmGroupViewController.swift
  Rollin_MVP/Rollin_MVP/Screens/CreateGroup/GroupCodeSharingViewController.swift
  Rollin_MVP/Rollin_MVP/Screens/CreateGroup/SetThemeViewController.swift
  Rollin_MVP/Rollin_MVP/Screens/ParticipateGroup/ConfirmGroupWhileParticipateViewController.swift
Labels: feature

#126 그룹 내에서 코드를 복사하여 공유를 할 수 있도록 합니다
  Rollin_MVP/Rollin_MVP/Screens/GroupDetailView/GroupDetailViewController.swift
Labels: feature

#129 WriteRollingPaperViewController 의 전체적인 코드 리팩토링
  Rollin_MVP/Rollin_MVP/Screens/WriteRollingPaper/View/PostView.swift
  Rollin_MVP/Rollin_MVP/Screens/WriteRollingPaper/WriteRollingPaperViewController.swift
Labels: refactoring

#130 그룹 생성 시의 글자수 제한을 변경합니다
  Rollin_MVP/Rollin_MVP/Screens/CreateGroup/SetGroupNameWhileCreatingGroupViewController.swift
Labels: refactoring

#122 로그인 로직 리펙토링 및 오류 수정
  Rollin_MVP/Rollin_MVP.xcodeproj/project.pbxproj
  Rollin_MVP/Rollin_MVP/App/SceneDelegate.swift
  Rollin_MVP/Rollin_MVP/Screens/AppMain/MainViewController.swift
  Rollin_MVP/Rollin_MVP/Screens/Base.lproj/Main.storyboard
  Rollin_MVP/Rollin_MVP/Screens/LoginSetNickName/SetNickNameWhileLoginViewController.swift
  Rollin_MVP/Rollin_MVP/Screens/LoginView/LoginViewController.swift
Labels: refactoring

#132 그룹 내에서 본인 롤링페이퍼를 식별할 수 있는 북마크를 추가합니다
  Rollin_MVP/Rollin_MVP/Resources/Assets.xcassets/bookmark.imageset/Contents.json
  Rollin_MVP/Rollin_MVP/Resources/Assets.xcassets/bookmark.imageset/bookmark.svg
  Rollin_MVP/Rollin_MVP/Screens/GroupDetailView/GroupDetailViewController.swift
Labels: feature

#135 SettingView 레이아웃 구현
  Rollin_MVP/Rollin_MVP.xcodeproj/project.pbxproj
  Rollin_MVP/Rollin_MVP/Screens/Base.lproj/Main.storyboard
  Rollin_MVP/Rollin_MVP/Screens/Setting/SettingViewController.swift
  Rollin_MVP/Rollin_MVP/Screens/Setting/ViewComponents/SettingTableViewCell.swift
Labels: feature

#139 SettingView의 페이지 이동 로직을 구현합니다
  Rollin_MVP/Rollin_MVP.xcodeproj/project.pbxproj
  Rollin_MVP/Rollin_MVP/Screens/AppMain/MainViewController.swift
  Rollin_MVP/Rollin_MVP/Screens/Base.lproj/Main.storyboard
  Rollin_MVP/Rollin_MVP/Screens/Setting/AppInfoWebViewController.swift
  Rollin_MVP/Rollin_MVP/Screens/Setting/ResetNicknameViewController.swift
  Rollin_MVP/Rollin_MVP/Screens/Setting/SettingViewController.swift
Labels: feature

#140 포스트없는 경우 무한로딩 해결입니다
  Rollin_MVP/Rollin_MVP/Screens/AppMain/MainViewController.swift
Labels: fix logic

#142 설정창에서 앱 관련 정보들을 웹뷰로 확인합니다
  Rollin_MVP/Rollin_MVP.xcodeproj/project.pbxproj
  Rollin_MVP/Rollin_MVP/Screens/Setting/AppInfoWebViewController.swift
  Rollin_MVP/Rollin_MVP/Screens/Setting/Reachability.swift
  Rollin_MVP/Rollin_MVP/Screens/Setting/SettingViewController.swift
Labels: feature

#143 동적 콜렉션뷰와 디테일 하프 모달을 리팩토링하였습니다.
  Rollin_MVP/Rollin_MVP.xcodeproj/project.pbxproj
  Rollin_MVP/Rollin_MVP/Firebase/API/RollingPaperPostAPI.swift
  Rollin_MVP/Rollin_MVP/Model/Group.swift
  Rollin_MVP/Rollin_MVP/Model/GroupUserRollingPaper.swift
  Rollin_MVP/Rollin_MVP/Model/PostRollingPaper/PostData.swift
  Rollin_MVP/Rollin_MVP/Model/PostRollingPaper/PostRollingPaperModel.swift
  Rollin_MVP/Rollin_MVP/Model/RollingPaperPostModel.swift
  Rollin_MVP/Rollin_MVP/Screens/DetailRollingPaper/DetailRollingPaperViewController.swift
  Rollin_MVP/Rollin_MVP/Screens/DetailRollingPaper/RollingPaperView.swift
  Rollin_MVP/Rollin_MVP/Screens/GroupDetailView/GroupDetailViewController.swift
  Rollin_MVP/Rollin_MVP/Screens/PostRollingPaper/PostRollingPaperView/PostRollingPaperCollectionViewCell.swift
  Rollin_MVP/Rollin_MVP/Screens/PostRollingPaper/PostRollingPaperViewContoller/PostViewController.swift
  Rollin_MVP/Rollin_MVP/Screens/WriteRollingPaper/WriteRollingPaperViewController.swift
Labels: refactoring

#137 포스트 신고기능 추가를 합니다
  Rollin_MVP/Rollin_MVP.xcodeproj/project.pbxproj
  Rollin_MVP/Rollin_MVP/Global/Extension+/Date+.swift
  Rollin_MVP/Rollin_MVP/Screens/DetailRollingPaper/DetailRollingPaperViewController.swift
Labels: feature

#145 설정창에서 닉네임 재설정창을 구현합니다.
  Rollin_MVP/Rollin_MVP/Screens/AppMain/MainViewController.swift
  Rollin_MVP/Rollin_MVP/Screens/Setting/ResetNicknameViewController.swift
Labels: feature

#146 설정창의 개발자에게 메일 남기기를 구현합니다
  Rollin_MVP/Rollin_MVP/Screens/Setting/SettingViewController.swift
Labels: feature

#152 로그아웃 및 회원탈퇴 기능 추가
  Rollin_MVP/Rollin_MVP/App/AppDelegate.swift
  Rollin_MVP/Rollin_MVP/Screens/Setting/SettingViewController.swift
Labels: feature
