Repository Chilli-Saewoo/Roll-in, pull requests merged in 2022-12, with the labels that each got.

#158 그룹원 롤링페이퍼 카드 UI를 수정합니다
  Rollin_MVP/Rollin_MVP/Resources/Assets.xcassets/Colors/cardBlue.colorset/Contents.json
  Rollin_MVP/Rollin_MVP/Resources/Assets.xcassets/Colors/cardDeepBlue.colorset/Contents.json
  Rollin_MVP/Rollin_MVP/Resources/Assets.xcassets/Colors/cardGreen.colorset/Contents.json
  Rollin_MVP/Rollin_MVP/Resources/Assets.xcassets/Colors/cardPink.colorset/Contents.json
  Rollin_MVP/Rollin_MVP/Resources/Assets.xcassets/Colors/cardPurple.colorset/Contents.json
  Rollin_MVP/Rollin_MVP/Resources/Assets.xcassets/Colors/cardRed.colorset/Contents.json
  Rollin_MVP/Rollin_MVP/Resources/Assets.xcassets/Colors/cardYellow.colorset/Contents.json
  Rollin_MVP/Rollin_MVP/Screens/GroupDetailView/GroupDetailViewController.swift
Labels: refactoring

#155 메인화면 버그해결
  Rollin_MVP/Rollin_MVP.xcodeproj/project.pbxproj
  Rollin_MVP/Rollin_MVP/Screens/AppMain/MainViewController.swift
  Rollin_MVP/Rollin_MVP/Screens/LoginSetNickName/SetNickNameWhileLoginViewController.swift
  Rollin_MVP/Rollin_MVP/Screens/LoginView/LoginViewController.swift
  Rollin_MVP/Rollin_MVP/Screens/Setting/SettingViewController.swift
Labels: fix logic

#163 소속된 그룹이 없을시 소속된 그룹 없음을 알려주는 뷰 추가
  Rollin_MVP/Rollin_MVP/Screens/AppMain/MainViewController.swift
Labels: fix ui

#166 그룹 내에서 닉네임을 변경하는 기능을 구현합니다
  Rollin_MVP/Rollin_MVP/Screens/Base.lproj/Main.storyboard
  Rollin_MVP/Rollin_MVP/Screens/PostRollingPaper/PostViewController.swift
  Rollin_MVP/Rollin_MVP/Screens/PostRollingPaper/ResetIngroupNicknameViewController.swift
Labels: feature

#169 카드 Cell에 DataSource가 들어가는 방식이 변경되었습니다.
  Rollin_MVP/Rollin_MVP.xcodeproj/project.pbxproj
  Rollin_MVP/Rollin_MVP/Model/Group.swift
  Rollin_MVP/Rollin_MVP/Screens/AppMain/MainViewController.swift
  Rollin_MVP/Rollin_MVP/Screens/GroupDetailView/CardSwiperCell.swift
  Rollin_MVP/Rollin_MVP/Screens/GroupDetailView/GroupDetailViewController.swift
  Rollin_MVP/Rollin_MVP/Screens/Setting/SettingViewController.swift
Labels: refactoring

#171 Change private post logic
  Rollin_MVP/Rollin_MVP/Screens/PostRollingPaper/PostRollingPaperCollectionViewCell.swift
  Rollin_MVP/Rollin_MVP/Screens/PostRollingPaper/PostViewController.swift
Labels: feature

#174 그룹원들의 롤링페이퍼에 인덱스바를 추가합니다
  Rollin_MVP/Rollin_MVP/Screens/GroupDetailView/GroupDetailViewController.swift
  Rollin_MVP/Rollin_MVP/Screens/GroupDetailView/IndexBarTableViewCell.swift
Labels: feature

#175 change private post logic 오류를 수정합니다
  Rollin_MVP/Rollin_MVP/Screens/PostRollingPaper/PostViewController.swift
Labels: fix logic

#176 포스트뷰의 테마 추가 및 작성뷰를 변경합니다
  Rollin_MVP/Rollin_MVP.xcodeproj/project.pbxproj
  Rollin_MVP/Rollin_MVP/Global/Extension+/UIColor+.swift
  Rollin_MVP/Rollin_MVP/Resources/Assets.xcassets/Colors/textBrown.colorset/Contents.json
  Rollin_MVP/Rollin_MVP/Resources/Assets.xcassets/Colors/textGold.colorset/Contents.json
  Rollin_MVP/Rollin_MVP/Resources/Assets.xcassets/Themes/Contents.json
  Rollin_MVP/Rollin_MVP/Resources/Assets.xcassets/Themes/deer.imageset/Contents.json
  Rollin_MVP/Rollin_MVP/Resources/Assets.xcassets/Themes/deer.imageset/dear.png
  Rollin_MVP/Rollin_MVP/Resources/Assets.xcassets/Themes/gingerBread.imageset/Contents.json
  Rollin_MVP/Rollin_MVP/Resources/Assets.xcassets/Themes/gingerBread.imageset/gingerBread.png
  Rollin_MVP/Rollin_MVP/Resources/Assets.xcassets/Themes/light.imageset/Contents.json
  Rollin_MVP/Rollin_MVP/Resources/Assets.xcassets/Themes/light.imageset/light.png
  Rollin_MVP/Rollin_MVP/Resources/Assets.xcassets/Themes/mistletoe.imageset/Contents.json
  Rollin_MVP/Rollin_MVP/Resources/Assets.xcassets/Themes/mistletoe.imageset/mistletoe.png
  Rollin_MVP/Rollin_MVP/Resources/Assets.xcassets/Themes/orangeStripe.imageset/Contents.json
  Rollin_MVP/Rollin_MVP/Resources/Assets.xcassets/Themes/orangeStripe.imageset/orangeStripe.png
  Rollin_MVP/Rollin_MVP/Resources/Assets.xcassets/Themes/redStripe.imageset/Contents.json
  Rollin_MVP/Rollin_MVP/Resources/Assets.xcassets/Themes/redStripe.imageset/redStripe.png
  Rollin_MVP/Rollin_MVP/Resources/Assets.xcassets/Themes/santa.imageset/Contents.json
  Rollin_MVP/Rollin_MVP/Resources/Assets.xcassets/Themes/santa.imageset/santa.png
  Rollin_MVP/Rollin_MVP/Resources/Assets.xcassets/Themes/snowman.imageset/Contents.json
  Rollin_MVP/Rollin_MVP/Resources/Assets.xcassets/Themes/snowman.imageset/snowman.png
  Rollin_MVP/Rollin_MVP/Screens/PostRollingPaper/PostViewController.swift
  Rollin_MVP/Rollin_MVP/Screens/WriteRollingPaper/ViewComponents/PostImageCollectionViewCell.swift
  Rollin_MVP/Rollin_MVP/Screens/WriteRollingPaper/ViewComponents/PostTextCollectionViewCell.swift
  Rollin_MVP/Rollin_MVP/Screens/WriteRollingPaper/ViewComponents/PostThemePickerView.swift
  Rollin_MVP/Rollin_MVP/Screens/WriteRollingPaper/ViewComponents/PostThemePickerViewCell.swift
  Rollin_MVP/Rollin_MVP/Screens/WriteRollingPaper/ViewComponents/PostView.swift
  Rollin_MVP/Rollin_MVP/Screens/WriteRollingPaper/WriteRollingPaperViewController.swift
Labels: feature

#179 이제 닉네임 String이 아닌 UID를 통해 유저를 가져옵니다.
  Rollin_MVP/Rollin_MVP.xcodeproj/project.pbxproj
  Rollin_MVP/Rollin_MVP/Screens/DetailRollingPaper/DetailRollingPaperViewController.swift
  Rollin_MVP/Rollin_MVP/Screens/PostRollingPaper/PostRollingPaperLayout.swift
  Rollin_MVP/Rollin_MVP/Screens/PostRollingPaper/PostViewController.swift
  Rollin_MVP/Rollin_MVP/Screens/WriteRollingPaper/WriteRollingPaperViewController.swift
Labels: fix logic
