Repository Chilli-Saewoo/Roll-in, pull requests merged in 2022-10, with the labels that each got.

#3 닉네임 화면의 UI를 프로젝트에 추가합니다.
  RollIn/RollIn.xcodeproj/project.pbxproj
  RollIn/RollIn/Global/Extension/UIApplication+.swift
  RollIn/RollIn/Global/Extension/UserDefaults+.swift
  RollIn/RollIn/Screens/Base.lproj/Main.storyboard
  RollIn/RollIn/Screens/NicknameSetting/NicknameSettingViewController.swift
Labels: feature

#12 닉네임을 설정하는 화면의 로직을 추가합니다.
  RollIn/RollIn.xcodeproj/project.pbxproj
  RollIn/RollIn/Global/Extension/UserDefaults+.swift
  RollIn/RollIn/Model/User.swift
  RollIn/RollIn/Screens/Base.lproj/Main.storyboard
  RollIn/RollIn/Screens/NicknameSetting/NicknameSettingViewController.swift
  RollIn/RollIn/Screens/QRCodeEnroll/QRCodeEnrollViewController.swift
Labels: feature

#7 롤링페이퍼 보여줄 임시 테이블뷰 구현
  RollIn/RollIn.xcodeproj/project.pbxproj
  RollIn/RollIn/Screens/Rollingpaper/RollingpaperViewController.swift
  RollIn/RollIn/Screens/Rollingpaper/Views/RollingpaperTableViewCell.swift
Labels: feature

#17 qr 생성창과 해당 로직을을 추가합니다.
  RollIn/RollIn.xcodeproj/project.pbxproj
  RollIn/RollIn/App/SceneDelegate.swift
  RollIn/RollIn/Screens/Base.lproj/Main.storyboard
  RollIn/RollIn/Screens/NicknameSetting/NicknameSettingViewController.swift
  RollIn/RollIn/Screens/QRCodeEnroll/QRCodeEnrollViewController.swift
Labels: feature

#22 Firebase 데이터 변경에 따라 TV화면(iPAD)가 반응형으로 데이터를 수신합니다
  HalloweenTF_iPad/HalloweenTF_iPad.xcodeproj/project.pbxproj
  HalloweenTF_iPad/HalloweenTF_iPad.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  HalloweenTF_iPad/HalloweenTF_iPad/ContentView.swift
  HalloweenTF_iPad/HalloweenTF_iPad/GoogleService-Info.plist
  HalloweenTF_iPad/HalloweenTF_iPad/HalloweenTF_iPadApp.swift
Labels: feature

#20 Rolling paper가 firebase 데이터 변화를 수신대기합니다.
  RollIn/RollIn.xcodeproj/project.pbxproj
  RollIn/RollIn/Model/Note.swift
  RollIn/RollIn/Screens/Rollingpaper/RollingpaperViewController.swift
  RollIn/RollIn/Screens/Rollingpaper/Views/RollingpaperView.swift
Labels: feature

#27 QR화면의 HIFI UI 적용입니다.
  RollIn/RollIn.xcodeproj/project.pbxproj
  RollIn/RollIn/Global/Extension/UILabel+.swift
  RollIn/RollIn/Screens/QRCodeEnroll/QRCodeEnrollViewController.swift
Labels: feature

#31 아이패드(TV화면)에 QR코드를 시간이 지남에 따라 변경하며 보여줍니다
  HalloweenTF_iPad/HalloweenTF_iPad.xcodeproj/project.pbxproj
  HalloweenTF_iPad/HalloweenTF_iPad/Assets.xcassets/AppIcon.appiconset/Contents.json
  HalloweenTF_iPad/HalloweenTF_iPad/Assets.xcassets/background.imageset/Contents.json
  HalloweenTF_iPad/HalloweenTF_iPad/Assets.xcassets/background.imageset/background.png
  HalloweenTF_iPad/HalloweenTF_iPad/ContentView.swift
Labels: feature

#28 닉네임 화면 하이파이UI 적용합니다
  RollIn/RollIn.xcodeproj/project.pbxproj
  RollIn/RollIn/Global/Extension/UITextField+.swift
  RollIn/RollIn/Screens/NicknameSetting/NicknameSettingViewController.swift
Labels: feature

#30 스티커에 Message와 Sender가 들어갑니다
  RollIn/RollIn.xcodeproj/project.pbxproj
  RollIn/RollIn/App/UIColor＋.swift
  RollIn/RollIn/Resources/Assets.xcassets/sticker/Contents.json
  RollIn/RollIn/Resources/Assets.xcassets/sticker/batOrange.imageset/Contents.json
  RollIn/RollIn/Resources/Assets.xcassets/sticker/batOrange.imageset/batOrange.png
  RollIn/RollIn/Resources/Assets.xcassets/sticker/batPurple.imageset/Contents.json
  RollIn/RollIn/Resources/Assets.xcassets/sticker/batPurple.imageset/batPurple.png
  RollIn/RollIn/Resources/Assets.xcassets/sticker/carriageOrange.imageset/Contents.json
  RollIn/RollIn/Resources/Assets.xcassets/sticker/carriageOrange.imageset/carriageOrange.png
  RollIn/RollIn/Resources/Assets.xcassets/sticker/carriagePurple.imageset/Contents.json
  RollIn/RollIn/Resources/Assets.xcassets/sticker/carriagePurple.imageset/carriagePurple.png
  RollIn/RollIn/Resources/Assets.xcassets/sticker/ghostOrange.imageset/Contents.json
  RollIn/RollIn/Resources/Assets.xcassets/sticker/ghostOrange.imageset/ghostOrange.png
  RollIn/RollIn/Resources/Assets.xcassets/sticker/ghostPurple.imageset/Contents.json
  RollIn/RollIn/Resources/Assets.xcassets/sticker/ghostPurple.imageset/ghostPurple.png
  RollIn/RollIn/Resources/Assets.xcassets/sticker/pumpkinOrange.imageset/Contents.json
  RollIn/RollIn/Resources/Assets.xcassets/sticker/pumpkinOrange.imageset/pumpkinOrange.png
  RollIn/RollIn/Resources/Assets.xcassets/sticker/pumpkinPurple.imageset/Contents.json
  RollIn/RollIn/Resources/Assets.xcassets/sticker/pumpkinPurple.imageset/pumpkinPurple.png
  RollIn/RollIn/Resources/Assets.xcassets/sticker/skullOrange.imageset/Contents.json
  RollIn/RollIn/Resources/Assets.xcassets/sticker/skullOrange.imageset/skullOrange.png
  RollIn/RollIn/Resources/Assets.xcassets/sticker/skullPurple.imageset/Contents.json
  RollIn/RollIn/Resources/Assets.xcassets/sticker/skullPurple.imageset/skullPurple.png
  RollIn/RollIn/Resources/Assets.xcassets/stickerBackground/Contents.json
  RollIn/RollIn/Resources/Assets.xcassets/stickerBackground/batOrangeBackground.imageset/Contents.json
  RollIn/RollIn/Resources/Assets.xcassets/stickerBackground/batOrangeBackground.imageset/batOrangeBackground.png
  RollIn/RollIn/Resources/Assets.xcassets/stickerBackground/batPurpleBackground.imageset/Contents.json
  RollIn/RollIn/Resources/Assets.xcassets/stickerBackground/batPurpleBackground.imageset/batPurpleBackground.png
  RollIn/RollIn/Resources/Assets.xcassets/stickerBackground/carriageOrangeBackground.imageset/Contents.json
  RollIn/RollIn/Resources/Assets.xcassets/stickerBackground/carriageOrangeBackground.imageset/carriageOrangeBackground.png
  RollIn/RollIn/Resources/Assets.xcassets/stickerBackground/carriagePurpleBackground.imageset/Contents.json
  RollIn/RollIn/Resources/Assets.xcassets/stickerBackground/carriagePurpleBackground.imageset/carriagePurpleBackground.png
  RollIn/RollIn/Resources/Assets.xcassets/stickerBackground/ghostOrangeBackground.imageset/Contents.json
  RollIn/RollIn/Resources/Assets.xcassets/stickerBackground/ghostOrangeBackground.imageset/ghostOrangeBackground.png
  RollIn/RollIn/Resources/Assets.xcassets/stickerBackground/ghostPurpleBackground.imageset/Contents.json
  RollIn/RollIn/Resources/Assets.xcassets/stickerBackground/ghostPurpleBackground.imageset/ghostPurpleBackground.png
  RollIn/RollIn/Resources/Assets.xcassets/stickerBackground/pumpkinOrangeBackground.imageset/Contents.json
  RollIn/RollIn/Resources/Assets.xcassets/stickerBackground/pumpkinOrangeBackground.imageset/pumpkinOrangeBackground.png
  RollIn/RollIn/Resources/Assets.xcassets/stickerBackground/pumpkinPurpleBackground.imageset/Contents.json
  RollIn/RollIn/Resources/Assets.xcassets/stickerBackground/pumpkinPurpleBackground.imageset/pumpkinPurpleBackground.png
  RollIn/RollIn/Resources/Assets.xcassets/stickerBackground/skullOrangeBackground.imageset/Contents.json
  RollIn/RollIn/Resources/Assets.xcassets/stickerBackground/skullOrangeBackground.imageset/skullOrangeBackground.png
  RollIn/RollIn/Resources/Assets.xcassets/stickerBackground/skullPurpleBackground.imageset/Contents.json
  RollIn/RollIn/Resources/Assets.xcassets/stickerBackground/skullPurpleBackground.imageset/skullPurpleBackground.png
  RollIn/RollIn/Screens/Base.lproj/Main.storyboard
  RollIn/RollIn/Screens/QRCodeEnroll/QRCodeEnrollViewController.swift
  RollIn/RollIn/Screens/QRShowing/QRShowingViewController.swift
  RollIn/RollIn/Screens/Rollingpaper/RollingpaperViewController.swift
  RollIn/RollIn/Screens/Rollingpaper/Views/NoteView.swift
  RollIn/RollIn/Screens/Rollingpaper/Views/RollingpaperView.swift
Labels: feature

#34 닉네임 화면 하이파이 UI 적용하기
  RollIn/RollIn.xcodeproj/project.pbxproj
  RollIn/RollIn/Global/Extension/UITextField+.swift
  RollIn/RollIn/Screens/NicknameSetting/NicknameSettingViewController.swift
Labels: feature

#36 user가 저장될 때 timestamp도 함께 저장됩니다.
  RollIn/RollIn/Screens/NicknameSetting/NicknameSettingViewController.swift
  RollIn/RollIn/Screens/Rollingpaper/RollingpaperViewController.swift
  RollIn/RollIn/Screens/Rollingpaper/Views/NoteView.swift
  RollIn/RollIn/Screens/Rollingpaper/Views/RollingpaperView.swift
Labels: feature

#39 QRCode, Nickname 화면에 디자인 피드백 반영입니다.
  RollIn/RollIn.xcodeproj/project.pbxproj
  RollIn/RollIn/Screens/Base.lproj/Main.storyboard
  RollIn/RollIn/Screens/NicknameSetting/NicknameSettingViewController.swift
  RollIn/RollIn/Screens/QRCodeEnroll/QRCodeEnrollViewController.swift
Labels: feature, fix ui

#40 qr코드 이미지를 선명하게 합니다
  HalloweenTF_iPad/HalloweenTF_iPad/ContentView.swift
Labels: feature, fix logic

#42 Nickname 뷰에서 공백 입력시에 다음 페이지로 넘어가지 않도록 합니다.
  RollIn/RollIn/Screens/NicknameSetting/NicknameSettingViewController.swift
Labels: feature
